// Generated by https://quicktype.io

export interface Caja {
  id: number;
  numEmpaque: string;
  numEnvio: string;
  estado: Estado;
  listDocumento: ListDocumento[];
}

export interface Estado {
  codigo: string;
  descripcion: string;
}

export interface ListDocumento {
  id: number;
  tipoDocu: AreaOrigen;
  areaOrigen: AreaOrigen;
  numSerieDocu: string;
  numPaquete: string;
  numFolios: number;
  estado: Estado;
}

export interface AreaOrigen {
  codigo: string;
}
